/// Flutter icons DBank
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DBank
///      fonts:
///       - asset: fonts/DBank.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DBank {
  DBank._();

  static const _kFontFam = 'DBank';
  static const String? _kFontPkg = null;

  static const IconData android = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expand_less_black_24dp = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData public_black_24dp = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData responsive = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData support = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData two_tone = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
